CREATE TABLE PERSON
(	id		VARCHAR(32) 	PRIMARY KEY,
	displayName	VARCHAR(255),
	email	    	VARCHAR(255),
	faculty	  	VARCHAR(50),
	phone		VARCHAR(15)
);

CREATE TABLE MANAGEMENT_ROLE
(	id		VARCHAR(32)	PRIMARY KEY,
	roleName	VARCHAR(255)	NOT NULL UNIQUE,
	updateTime	DATETIME	NOT NULL
);

CREATE TABLE CATEGORY
(	id		INT		IDENTITY(0,1)	PRIMARY KEY,
	categoryName	VARCHAR(255)	NOT NULL UNIQUE,
	parentId	INT,
	updateTime	DATETIME	NOT NULL,
FOREIGN KEY (parentId) REFERENCES CATEGORY(id)
	ON DELETE NO ACTION	  ON UPDATE NO ACTION);

CREATE TABLE ITEM
(	id		INT		IDENTITY(0,1)	PRIMARY KEY,
	itemName  	VARCHAR(255)	NOT NULL,
	categoryId	INT,
	updateTime	DATETIME	NOT NULL,
FOREIGN KEY (categoryId) REFERENCES CATEGORY(id) ON UPDATE CASCADE);

CREATE TABLE OVERLOOKS
(	roleId		VARCHAR(32),
	categoryId	INT,
PRIMARY KEY (roleId, categoryId),
FOREIGN KEY (roleId) REFERENCES MANAGEMENT_ROLE(id)
	ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (categoryId) REFERENCES CATEGORY(id)
	ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE RESERVATION
(	id		INT		IDENTITY(0,1)	PRIMARY KEY,
	personId	INT		NOT NULL,
	itemId		INT		NOT NULL,
	startTime	DATETIME	NOT NULL,
	endTime		DATETIME	NOT NULL,
	responderId	VARCHAR(32),
	respondTime	DATETIME,
	creationTime	DATETIME	NOT NULL,
FOREIGN KEY (itemId) REFERENCES ITEM(id)
	ON UPDATE CASCADE,
FOREIGN KEY (responderId) REFERENCES PERSON(id)
	ON UPDATE CASCADE);
