DROP PROCEDURE IF EXISTS spGetCategories;
DROP PROCEDURE IF EXISTS spGetConsumables;
DROP PROCEDURE IF EXISTS spGetNonConsumables;

CREATE PROCEDURE spGetCategories AS
BEGIN
SET NOCOUNT ON
SELECT * FROM CATEGORY
END;

CREATE PROCEDURE spGetConsumables AS
BEGIN
SET NOCOUNT ON
SELECT * FROM ITEM
END;

CREATE PROCEDURE spGetNonConsumables AS
BEGIN
SET NOCOUNT ON
SELECT * FROM ITEM
END;
